export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';
export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';
export const PRODUCT_REVIEW_REQUEST = 'PRODUCT_REVIEW_REQUEST';
export const PRODUCT_REVIEW_SUCCESS = 'PRODUCT_REVIEW_SUCCESS';
export const PRODUCT_REVIEW_FAIL = 'PRODUCT_REVIEW_FAIL';
//
export const GET_PRODUCT_AUTHORS_REQUEST = 'GET_PRODUCT_AUTHORS_REQUEST';
export const GET_PRODUCT_AUTHORS_SUCCESS = 'GET_PRODUCT_AUTHORS_SUCCESS';
export const GET_PRODUCT_AUTHORS_FAIL = 'GET_PRODUCT_AUTHORS_FAIL';
export const GET_PRODUCT_AUTHORS_RESET = 'GET_PRODUCT_AUTHORS_RESET';
export const GET_PRODUCT_PUBLISHERS_REQUEST = 'GET_PRODUCT_PUBLISHERS_REQUEST';
export const GET_PRODUCT_PUBLISHERS_SUCCESS = 'GET_PRODUCT_PUBLISHERS_SUCCESS';
export const GET_PRODUCT_PUBLISHERS_FAIL = 'GET_PRODUCT_PUBLISHERS_FAIL';
export const GET_PRODUCT_PUBLISHERS_RESET = 'GET_PRODUCT_PUBLISHERS_RESET';
export const GET_PRODUCT_CATEGORIES_REQUEST = 'GET_PRODUCT_CATEGORIES_REQUEST';
export const GET_PRODUCT_CATEGORIES_SUCCESS = 'GET_PRODUCT_CATEGORIES_SUCCESS';
export const GET_PRODUCT_CATEGORIES_RESET = 'GET_PRODUCT_CATEGORIES_RESET';
export const GET_PRODUCT_CATEGORIES_FAIL = 'GET_PRODUCT_CATEGORIES_FAIL';

export const POST_PRODUCT_AUTHORS_REQUEST = 'POST_PRODUCT_AUTHORS_REQUEST';
export const POST_PRODUCT_AUTHORS_SUCCESS = 'POST_PRODUCT_AUTHORS_SUCCESS';
export const POST_PRODUCT_AUTHORS_FAIL = 'POST_PRODUCT_AUTHORS_FAIL';
export const POST_PRODUCT_AUTHORS_RESET = 'POST_PRODUCT_AUTHORS_RESET';
export const POST_PRODUCT_PUBLISHERS_REQUEST =
  'POST_PRODUCT_PUBLISHERS_REQUEST';
export const POST_PRODUCT_PUBLISHERS_SUCCESS =
  'POST_PRODUCT_PUBLISHERS_SUCCESS';
export const POST_PRODUCT_PUBLISHERS_FAIL = 'POST_PRODUCT_PUBLISHERS_FAIL';
export const POST_PRODUCT_PUBLISHERS_RESET = 'POST_PRODUCT_PUBLISHERS_RESET';
export const POST_PRODUCT_CATEGORIES_REQUEST =
  'POST_PRODUCT_CATEGORIES_REQUEST';
export const POST_PRODUCT_CATEGORIES_SUCCESS =
  'POST_PRODUCT_CATEGORIES_SUCCESS';
export const POST_PRODUCT_CATEGORIES_RESET = 'POST_PRODUCT_CATEGORIES_RESET';
export const POST_PRODUCT_CATEGORIES_FAIL = 'POST_PRODUCT_CATEGORIES_FAIL';

export const ADMIN_POST_PRODUCT_REQUEST = 'ADMIN_POST_PRODUCT_REQUEST';
export const ADMIN_POST_PRODUCT_SUCCESS = 'ADMIN_POST_PRODUCT_SUCCESS';
export const ADMIN_POST_PRODUCT_FAIL = 'ADMIN_POST_PRODUCT_FAIL';
export const ADMIN_POST_PRODUCT_RESET = 'ADMIN_POST_PRODUCT_RESET';

export const ADMIN_UPDATE_PRODUCT_REQUEST = 'ADMIN_UPDATE_PRODUCT_REQUEST';
export const ADMIN_UPDATE_PRODUCT_SUCCESS = 'ADMIN_UPDATE_PRODUCT_SUCCESS';
export const ADMIN_UPDATE_PRODUCT_FAIL = 'ADMIN_UPDATE_PRODUCT_FAIL';
export const ADMIN_UPDATE_PRODUCT_RESET = 'ADMIN_UPDATE_PRODUCT_RESET';

export const ADMIN_DELETE_PRODUCT_REQUEST = 'ADMIN_DELETE_PRODUCT_REQUEST';
export const ADMIN_DELETE_PRODUCT_SUCCESS = 'ADMIN_DELETE_PRODUCT_SUCCESS';
export const ADMIN_DELETE_PRODUCT_FAIL = 'ADMIN_DELETE_PRODUCT_FAIL';
export const ADMIN_DELETE_PRODUCT_RESET = 'ADMIN_DELETE_PRODUCT_RESET';
