export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET';
export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';
export const USER_UPDATE_DETAILS_REQUEST = 'USER_UPDATE_DETAILS_REQUEST';
export const USER_UPDATE_DETAILS_SUCCESS = 'USER_UPDATE_DETAILS_SUCCESS';
export const USER_UPDATE_DETAILS_FAIL = 'USER_UPDATE_DETAILS_FAIL';
export const USER_UPDATE_DETAILS_RESET = 'USER_UPDATE_DETAILS_RESET';
export const USER_UPDATE_PASSWORD_REQUEST = 'USER_UPDATE_PASSWORD_REQUEST';
export const USER_UPDATE_PASSWORD_SUCCESS = 'USER_UPDATE_PASSWORD_SUCCESS';
export const USER_UPDATE_PASSWORD_FAIL = 'USER_UPDATE_PASSWORD_FAIL';
export const USER_UPDATE_PASSWORD_RESET = 'USER_UPDATE_PASSWORD_RESET';

//ADMIN
export const ALL_USERS_DETAILS_REQUEST = 'ALL_USERS_DETAILS_REQUEST';
export const ALL_USERS_DETAILS_SUCCESS = 'ALL_USERS_DETAILS_SUCCESS';
export const ALL_USERS_DETAILS_FAIL = 'ALL_USERS_DETAILS_FAIL';
export const ALL_USERS_DETAILS_RESET = 'ALL_USERS_DETAILS_RESET';

export const ADMIN_POST_USER_REQUEST = 'ADMIN_POST_USER_REQUEST';
export const ADMIN_POST_USER_SUCCESS = 'ADMIN_POST_USER_SUCCESS';
export const ADMIN_POST_USER_FAIL = 'ADMIN_POST_USER_FAIL';
export const ADMIN_POST_USER_RESET = 'ADMIN_POST_USER_RESET';

export const ADMIN_UPDATE_USER_REQUEST = 'ADMIN_UPDATE_USER_REQUEST';
export const ADMIN_UPDATE_USER_SUCCESS = 'ADMIN_UPDATE_USER_SUCCESS';
export const ADMIN_UPDATE_USER_FAIL = 'ADMIN_UPDATE_USER_FAIL';
export const ADMIN_UPDATE_USER_RESET = 'ADMIN_UPDATE_USER_RESET';

export const ADMIN_DELETE_USER_REQUEST = 'ADMIN_DELETE_USER_REQUEST';
export const ADMIN_DELETE_USER_SUCCESS = 'ADMIN_DELETE_USER_SUCCESS';
export const ADMIN_DELETE_USER_FAIL = 'ADMIN_DELETE_USER_FAIL';
export const ADMIN_DELETE_USER_RESET = 'ADMIN_DELETE_USER_RESET';
